### ISSUE TITLE
Doubts about the API

### ISSUE THREAD

**Issue by BrunoMine** [tenplus1/mobs_redo#18]
I was really surprised about this work. I liked a lot and want to help with the sharing of this project. I beg that you have patience to help me with some things.
I'm translating the current API for my language on [api-pt_BR.txt](https://github.com/BrunoMine/mobs_redo/blob/api-translate-pt_BR/api-pt_BR.txt).
I had some questions about some things. I would like a short explanation of each.

1. '[walk_chance](https://github.com/tenplus1/mobs_redo/blob/master/api.txt#L42)' and '[jump_chance](https://github.com/tenplus1/mobs_redo/blob/master/api.txt#L43)' seem confusing. This is a chance of a mob walking or skip each particular time? If so, how the chances are calculated?

2. '[recovery_time](https://github.com/tenplus1/mobs_redo/blob/master/api.txt#L53)' seems to have a strange operation. The mob recover health after half a second?

3. '[light_damage](https://github.com/tenplus1/mobs_redo/blob/master/api.txt#L69)' is referring to the light of day?

4. About '[fall_damage](https://github.com/tenplus1/mobs_redo/blob/master/api.txt#L70)'. What kind of value is that? acceleration, time or boolean? How it behaves if the creature is too big and the height 6 seem derisory

5. In [line 90](https://github.com/tenplus1/mobs_redo/blob/master/api.txt#L90) the simbol `+/-` refers to is an approximate value?

6. '[reach](https://github.com/tenplus1/mobs_redo/blob/master/api.txt#L91)' is the range of the shot?

7. '[active_object_count](https://github.com/tenplus1/mobs_redo/blob/master/api.txt#L150)' I really do not understand it.

8. '[drop](https://github.com/tenplus1/mobs_redo/blob/master/api.txt#L180)' drop the arrow or the node?

**Comment by tenplus1** [comment]
'walk_chance' is usually decided by picking a random number from 1 to 100 and if it's lower than walk_chance then mob entity will walk.

'recovery_time' is disabled and instead 'knock_back' is used in seconds (3 by default).

'light_damage' is just that, damage sustained when in sunlight.

'fall_damage' is 0 for 0ff and 1 for on (I was going to add other settings hence the 0 and 1 instead of true/false).

'shoot_offset' is typically 1 for middle of mob, but if it's a tall mob then 2 (1 block higher) or even 0 to shoot from foot level.

'reach' is the arm length of mob when standing and hitting player.

'active_object_count' is the number of active entities in a loaded area affected by abm's, when spawning mobs for instance you can set number of mobs to 3 so that only 3 entities can be active in this area to stop overspawning.

'drop' is self explanatory, when true any arrows (or arrow entities) hitting a solid surface will drop as an item for players to pick up e.g. shuriken.
