### ISSUE TITLE
Misleading chat command reply when trying to spawn mob with only_peaceful_mobs=true 

### ISSUE THREAD

**Issue by kingoscargames** [tenplus1/mobs_redo#60]
https://github.com/Wuzzy2/MineClone2-Bugs/issues/266

**Comment by tenplus1** [comment]
/summon is not a command in mobs redo api.

**Comment by kingoscargames** [comment]
it is the same as spawnentity

**Comment by tenplus1** [comment]
/spawnentity is a minetest comment and not part of the mobs redo api.

**Comment by Wuzzy2** [comment]
I think I should explain the problem here:

* `only_peaceful_mobs=true`
* You do `/spawnentity mobs_example:pumba`
* Mob is immediately deleted after spawning because of `only_peaceful_mobs=true`
* Player is confused becaue no mob spawned although `/spawnentity` has been used

This is an usability problem. A warning message might be nice. As far I know there is no function or command to spawn a mob.

Can't be fixed in Minetest because Minetest needs to know Mobs Redo then (this will never happen).

Any ideas on how to fix this usability problem anyway?

**Comment by tenplus1** [comment]
I could override the /spawnentity command itself but would rather not, and really do not wish to spam chat each time a monster fails to spawn (maybe an initial message on connect will suffice).  A player should know wether they are in peaceful mode or not going by there own settings or server description.
